- build.gradle
- src/main/java/com/example/springserver/application/customer/CustomerController.java
- src/main/java/com/example/springserver/domain/customer/converter/CustomerConverter.java
- src/main/java/com/example/springserver/domain/customer/dto/CustomerRequestDTO.java
- src/main/java/com/example/springserver/domain/customer/dto/CustomerResponseDTO.java
- src/main/java/com/example/springserver/domain/customer/repository/CustomerRepository.java
- src/main/java/com/example/springserver/domain/customer/service/CustomerService.java
- src/main/java/com/example/springserver/domain/keyword/repository/KeywordMappingRepository.java
- src/main/java/com/example/springserver/domain/keyword/service/KeywordService.java
- src/main/java/com/example/springserver/entity/Cafe.java
- src/main/java/com/example/springserver/entity/Customer.java
- src/main/java/com/example/springserver/entity/Review.java
- src/main/java/com/example/springserver/entity/UserEntity.java
- src/main/java/com/example/springserver/global/common/api/status/ErrorStatus.java
- src/main/java/com/example/springserver/global/config/S3Config.java
- src/main/java/com/example/springserver/global/s3/S3Service.java
- #11 
- S3 연동 및 이미지 등록 후 url 반환 Service 작성
- searchCustomer API
- editCustomer API
> S3 연동 및 Customer 관련 API 추가

- src/main/java/com/example/springserver/application/auth/AuthController.java
- src/main/java/com/example/springserver/domain/auth/service/SignUpService.java
- src/main/java/com/example/springserver/domain/user/repository/UserRepository.java
- src/main/java/com/example/springserver/domain/user/service/UserService.java
- src/main/java/com/example/springserver/global/common/api/status/ErrorStatus.java
- #19 
입력받은 이메일을 기반으로 회원가입 유무 체크
> feat: verifyEmail API에서 회원가입 유무 확인

- src/main/java/com/example/springserver/application/cafe/CafeController.java
- src/main/java/com/example/springserver/domain/cafe/converter/CafeConverter.java
- src/main/java/com/example/springserver/domain/cafe/dto/CafeRequestDTO.java
- src/main/java/com/example/springserver/domain/cafe/dto/CafeResponseDTO.java
- src/main/java/com/example/springserver/domain/cafe/repository/CafeRepository.java
- src/main/java/com/example/springserver/domain/cafe/service/CafeService.java
- src/main/java/com/example/springserver/domain/customer/service/CustomerService.java
- src/main/java/com/example/springserver/entity/Cafe.java
- src/main/java/com/example/springserver/global/common/api/status/ErrorStatus.java
- src/main/java/com/example/springserver/global/config/RedisConfig.java
- #23 
editCafe API구현 (테스트x, 레디스 위치저장 x)
> 카페 정보 수정 API 구현

- src/main/java/com/example/springserver/application/cafe/CafeController.java
- src/main/java/com/example/springserver/domain/cafe/converter/CafeConverter.java
- src/main/java/com/example/springserver/domain/cafe/dto/CafeResponseDTO.java
- src/main/java/com/example/springserver/domain/cafe/service/CafeService.java
- src/main/java/com/example/springserver/entity/Keyword.java
- src/main/java/com/example/springserver/global/common/api/status/ErrorStatus.java
- #25 
- 카페 광고 등록 및 수정을 postCafeAdv로 통합
- user - cafe, customer - keywordMapping 간의 연관관계에서 부모에 CASCADE.REMOVE 추가 (부모가 삭제되면 자식도 삭제됨)
> feat: 카페 광고 이미지 업로드 구현 + 부모/자식 간 CASCADE 작성

- src/main/java/com/example/springserver/application/cafe/CafeController.java
- src/main/java/com/example/springserver/application/customer/CustomerController.java
- src/main/java/com/example/springserver/domain/auth/service/AuthorizationService.java
- src/main/java/com/example/springserver/domain/auth/service/EmailService.java
- src/main/java/com/example/springserver/domain/cafe/converter/CafeConverter.java
- src/main/java/com/example/springserver/domain/cafe/dto/CafeRequestDTO.java
- src/main/java/com/example/springserver/domain/cafe/dto/CafeResponseDTO.java
- src/main/java/com/example/springserver/domain/cafe/repository/CafeRepository.java
- src/main/java/com/example/springserver/domain/cafe/repository/StampRewardRepository.java
- src/main/java/com/example/springserver/domain/cafe/service/CafeService.java
- src/main/java/com/example/springserver/entity/Cafe.java
- src/main/java/com/example/springserver/entity/StampReward.java
- src/main/java/com/example/springserver/global/common/api/status/ErrorStatus.java
- #31 
- postStampReward 
- editStampReward 
- deleteStampReward 
- 인증 코드 8자리 -> 6자리 변경
> 스탬프 리워드 관련 API 구현

- src/main/java/com/example/springserver/application/stamp/StampController.java
- src/main/java/com/example/springserver/domain/cafe/repository/CafeRepository.java
- src/main/java/com/example/springserver/domain/cafe/service/CafeService.java
- src/main/java/com/example/springserver/domain/customer/repository/CustomerRepository.java
- src/main/java/com/example/springserver/domain/customer/service/CustomerService.java
- src/main/java/com/example/springserver/domain/stamp/converter/StampConverter.java
- src/main/java/com/example/springserver/domain/stamp/dto/StampRequestDTO.java
- src/main/java/com/example/springserver/domain/stamp/dto/StampResponseDTO.java
- src/main/java/com/example/springserver/domain/stamp/repository/StampBoardRepository.java
- src/main/java/com/example/springserver/domain/stamp/repository/StampRepository.java
- src/main/java/com/example/springserver/domain/stamp/service/StampBoardService.java
- src/main/java/com/example/springserver/domain/stamp/service/StampService.java
- src/main/java/com/example/springserver/entity/Cafe.java
- src/main/java/com/example/springserver/entity/Customer.java
- src/main/java/com/example/springserver/entity/Stamp.java
- src/main/java/com/example/springserver/entity/StampBoard.java
- src/main/java/com/example/springserver/global/common/api/status/ErrorStatus.java
- #31 
- postStamp API
- useStamp API
- Cafe, Customer Validate 함수 설정
- Cafe, Customer, StampBoard, Stamp 사이의 CASCADE 설정
> feat: 스탬프 적립 및 사용 API 구현

- src/main/java/com/example/springserver/application/customer/CustomerController.java
- src/main/java/com/example/springserver/domain/customer/converter/CustomerConverter.java
- src/main/java/com/example/springserver/domain/customer/dto/CustomerResponseDTO.java
- src/main/java/com/example/springserver/domain/customer/service/CustomerService.java
- src/main/java/com/example/springserver/domain/stamp/converter/StampConverter.java
- src/main/java/com/example/springserver/domain/stamp/dto/StampResponseDTO.java
- src/main/java/com/example/springserver/domain/stamp/repository/StampBoardRepository.java
- src/main/java/com/example/springserver/domain/stamp/service/StampBoardService.java
- #35 
소비자의 메인 화면에 들어가는 스탬프 보드 조회 API
> feat: 스탬프 보드 조회 API

- src/main/java/com/example/springserver/domain/cafe/service/CafeService.java
- src/main/java/com/example/springserver/domain/stamp/repository/StampBoardRepository.java
- src/main/java/com/example/springserver/domain/stamp/service/StampBoardService.java
- src/main/java/com/example/springserver/entity/BaseEntity.java
- src/main/java/com/example/springserver/entity/Cafe.java
- src/main/java/com/example/springserver/entity/Customer.java
- src/main/java/com/example/springserver/entity/Stamp.java
- src/main/java/com/example/springserver/entity/StampBoard.java
- src/main/java/com/example/springserver/entity/StampReward.java
- src/main/java/com/example/springserver/entity/UserEntity.java
- #41 
- 칼럼명 snake_case로 통일을 위한 Entity파일 수정
- getMyCafe Query 수정
> refactor: DB의 column명 snake_case로 통일

- src/main/java/com/example/springserver/application/admin/AdminController.java
- src/main/java/com/example/springserver/domain/admin/converter/AdminConverter.java
- src/main/java/com/example/springserver/domain/admin/dto/AdminRequestDTO.java
- src/main/java/com/example/springserver/domain/admin/dto/AdminResponseDTO.java
- src/main/java/com/example/springserver/domain/admin/service/AdminService.java
- src/main/java/com/example/springserver/global/config/SecurityConfig.java
- https://github.com/CookieMoa/Server/issues/43
- /admin/dashboard 관리자 대시보드 조회 API 개발
> feat: 관리자 대시보드 조회 API 개발

- src/main/java/com/example/springserver/domain/admin/service/AdminService.java
- src/main/java/com/example/springserver/domain/log/converter/StampLogConverter.java
- src/main/java/com/example/springserver/domain/log/enums/StampLogStatus.java
- src/main/java/com/example/springserver/domain/log/repository/StampLogRepository.java
- src/main/java/com/example/springserver/domain/log/service/StampLogService.java
- src/main/java/com/example/springserver/domain/stamp/service/StampService.java
- src/main/java/com/example/springserver/entity/StampLog.java
- https://github.com/CookieMoa/Server/issues/45
- 스탬프 로그 기록 로직 개발
- 대시보드 스탬프 개수 로직 추가
> feat: 스탬프 로그 기록 로직 개발

- src/main/java/com/example/springserver/application/admin/AdminController.java
- src/main/java/com/example/springserver/domain/admin/converter/AdminConverter.java
- src/main/java/com/example/springserver/domain/admin/dto/AdminResponseDTO.java
- src/main/java/com/example/springserver/domain/admin/service/AdminService.java
- src/main/java/com/example/springserver/domain/cafe/repository/CafeRepository.java
- src/main/java/com/example/springserver/domain/cafe/service/CafeService.java
- src/main/java/com/example/springserver/domain/customer/repository/CustomerRepository.java
- src/main/java/com/example/springserver/domain/customer/service/CustomerService.java
- src/main/java/com/example/springserver/entity/StampLog.java
- https://github.com/CookieMoa/Server/issues/47
- 최근 가입 유저 조회 API
- 최근 가입 카페 조회 API
> feat: 최근 가입 유저, 카페 조회 api 개발

- src/main/java/com/example/springserver/application/admin/AdminController.java
- src/main/java/com/example/springserver/domain/admin/converter/AdminConverter.java
- src/main/java/com/example/springserver/domain/admin/dto/AdminResponseDTO.java
- src/main/java/com/example/springserver/domain/admin/service/AdminService.java
- src/main/java/com/example/springserver/domain/log/repository/StampLogRepository.java
- https://github.com/CookieMoa/Server/issues/49
- 시간대별 스탬프 거래수 조회 API 개발
> feat: 시간대별 스탬프 거래수 조회 API 개발

- src/main/java/com/example/springserver/application/cafe/CafeController.java
- src/main/java/com/example/springserver/domain/cafe/converter/CafeConverter.java
- src/main/java/com/example/springserver/domain/cafe/dto/CafeRequestDTO.java
- src/main/java/com/example/springserver/domain/cafe/dto/CafeResponseDTO.java
- src/main/java/com/example/springserver/domain/cafe/service/CafeService.java
- src/main/java/com/example/springserver/entity/Review.java
- src/main/java/com/example/springserver/entity/StampLog.java
- src/main/java/com/example/springserver/global/jwt/LoginFilter.java
- #51 
- postReview API 구현
- jwt Token 만료시간 24시간으로 변경
- StampLogStatus @Enumerated(String) 설정
> feat: postReview API 구현 + jwt token 만료시간 24시간으로 변경

- src/main/java/com/example/springserver/domain/cafe/converter/CafeConverter.java
- src/main/java/com/example/springserver/domain/cafe/service/CafeService.java
- src/main/java/com/example/springserver/domain/stamp/repository/StampBoardRepository.java
- src/main/java/com/example/springserver/domain/stamp/service/StampBoardService.java
- src/main/java/com/example/springserver/domain/stamp/service/StampService.java
- src/main/java/com/example/springserver/entity/Cafe.java
- #53 
- 카페 당 발급 쿠키 수, 사용 쿠키 수 현황 체크를 위한 칼럼 추가
- 본인 카페 조회에서 위의 칼럼을 이용한 조회 사용
> feat: Cafe에 totalStampCount, totalUsedStampCount 추가 후 조회에서 사용

- src/main/java/com/example/springserver/domain/cafe/repository/ReviewRepository.java
- src/main/java/com/example/springserver/domain/cafe/service/CafeService.java
- src/main/java/com/example/springserver/domain/cafe/service/ReviewService.java
- #55 
postReview 에서 review save 를 위한 reviewRepository+reviewService 작성
> fix: PostReview에서 review save 추가

- src/main/java/com/example/springserver/application/cafe/CafeController.java
- src/main/java/com/example/springserver/application/customer/CustomerController.java
- src/main/java/com/example/springserver/domain/cafe/converter/ReviewConverter.java
- src/main/java/com/example/springserver/domain/cafe/dto/CafeResponseDTO.java
- src/main/java/com/example/springserver/domain/cafe/repository/ReviewRepository.java
- src/main/java/com/example/springserver/domain/cafe/service/CafeService.java
- src/main/java/com/example/springserver/domain/cafe/service/ReviewService.java
- src/main/java/com/example/springserver/domain/customer/dto/CustomerResponseDTO.java
- src/main/java/com/example/springserver/domain/customer/service/CustomerService.java
- src/main/java/com/example/springserver/global/common/paging/CommonPageReq.java
- #58 
- search의 정렬 기준을 최신순으로 변경
- searchReview를 Customer, Cafe가 사용하는 DTO 통일
- searchCustomerReviews API 구현
> feat: searchCustomerReviews API 구현

- src/main/java/com/example/springserver/application/cafe/CafeController.java
- src/main/java/com/example/springserver/domain/cafe/service/CafeService.java
> feat: deleteCafeAdv API 구현 (test x)

- src/main/java/com/example/springserver/application/customer/CustomerController.java
- src/main/java/com/example/springserver/domain/customer/converter/CustomerConverter.java
- src/main/java/com/example/springserver/domain/customer/dto/CustomerResponseDTO.java
- src/main/java/com/example/springserver/domain/customer/service/CustomerService.java
- src/main/java/com/example/springserver/domain/log/repository/StampLogRepository.java
- src/main/java/com/example/springserver/domain/log/service/StampLogService.java
- src/main/java/com/example/springserver/entity/StampLog.java
- #66 
- 스탬프 로그 중 10일 이내의 데이터를 불러옴
- 그 중 pendingReview 값이 true이면 불러와서 카페 정보 반환 (리뷰 작성 가능)
> feat: searchPendingReview API 구현 (test x)

- src/main/java/com/example/springserver/domain/cafe/service/CafeService.java
- #63 
- postCafe, editCafe 에서 카페의 위치 정보 Redis 연동
> feat: postCafe, editCafe 카페 위치 정보 redis 저장

- src/main/java/com/example/springserver/application/admin/AdminController.java
- src/main/java/com/example/springserver/domain/admin/converter/AdminConverter.java
- src/main/java/com/example/springserver/domain/admin/dto/AdminResponseDTO.java
- src/main/java/com/example/springserver/domain/admin/service/AdminService.java
- src/main/java/com/example/springserver/domain/cafe/converter/CafeConverter.java
- src/main/java/com/example/springserver/domain/cafe/dto/CafeResponseDTO.java
- src/main/java/com/example/springserver/domain/cafe/repository/CafeRepository.java
- src/main/java/com/example/springserver/domain/cafe/service/CafeService.java
- src/main/java/com/example/springserver/domain/customer/converter/CustomerConverter.java
- src/main/java/com/example/springserver/domain/customer/dto/CustomerResponseDTO.java
- src/main/java/com/example/springserver/domain/customer/repository/CustomerRepository.java
- src/main/java/com/example/springserver/domain/customer/service/CustomerService.java
- src/main/java/com/example/springserver/domain/stamp/repository/StampBoardRepository.java
- src/main/java/com/example/springserver/domain/stamp/service/StampBoardService.java
- https://github.com/CookieMoa/Server/issues/72
- 카페, 유저 전체 조회 및 검색
> 카페, 유저 전체 조회 및 검색

- src/main/java/com/example/springserver/domain/customer/converter/CustomerConverter.java
- src/main/java/com/example/springserver/domain/customer/dto/CustomerResponseDTO.java
- src/main/java/com/example/springserver/domain/customer/service/CustomerService.java
- https://github.com/CookieMoa/Server/issues/74
- 관리자 유저 조회 댓글 정보 추가
> feat: 관리자 유저 조회 댓글 정보 추가

- src/main/java/com/example/springserver/application/admin/AdminController.java
- src/main/java/com/example/springserver/domain/admin/service/AdminService.java
- src/main/java/com/example/springserver/domain/cafe/converter/CafeConverter.java
- src/main/java/com/example/springserver/domain/cafe/dto/CafeResponseDTO.java
- src/main/java/com/example/springserver/domain/cafe/enums/CafeStatus.java
- src/main/java/com/example/springserver/domain/cafe/service/CafeService.java
- src/main/java/com/example/springserver/domain/customer/converter/CustomerConverter.java
- src/main/java/com/example/springserver/domain/customer/dto/CustomerResponseDTO.java
- src/main/java/com/example/springserver/domain/customer/service/CustomerService.java
- src/main/java/com/example/springserver/domain/stamp/service/StampService.java
- src/main/java/com/example/springserver/entity/Cafe.java
- src/main/java/com/example/springserver/global/common/api/status/ErrorStatus.java
- https://github.com/CookieMoa/Server/issues/81
- 유저, 카페 정지 및 정지 해제
> feat: 유저, 카페 정지 및 정지 해제

- src/main/java/com/example/springserver/domain/cafe/converter/ReviewConverter.java
- src/main/java/com/example/springserver/domain/cafe/repository/ReviewRepository.java
- src/main/java/com/example/springserver/domain/cafe/service/CafeService.java
- src/main/java/com/example/springserver/domain/cafe/service/ReviewService.java
- src/main/java/com/example/springserver/domain/customer/service/CustomerService.java
- src/main/java/com/example/springserver/entity/Review.java
- https://github.com/CookieMoa/Server/issues/83
- 리뷰 작성시 악성 리뷰 판단
> feat: 악성 리뷰 판단

- src/main/java/com/example/springserver/application/admin/AdminController.java
- src/main/java/com/example/springserver/domain/admin/service/AdminService.java
- src/main/java/com/example/springserver/domain/cafe/repository/ReviewRepository.java
- src/main/java/com/example/springserver/domain/cafe/service/CafeService.java
- src/main/java/com/example/springserver/domain/cafe/service/ReviewService.java
- https://github.com/CookieMoa/Server/issues/85
-  키워드 추출
> feat: 키워드 추출

- src/main/java/com/example/springserver/application/admin/AdminController.java
- src/main/java/com/example/springserver/application/ai/AiController.java
- src/main/java/com/example/springserver/domain/admin/service/AdminService.java
- src/main/java/com/example/springserver/domain/ai/converter/AiConverter.java
- src/main/java/com/example/springserver/domain/ai/dto/AiResponseDTO.java
- src/main/java/com/example/springserver/domain/ai/service/AiService.java
- src/main/java/com/example/springserver/global/common/api/status/ErrorStatus.java
- src/main/java/com/example/springserver/global/config/SecurityConfig.java
- https://github.com/CookieMoa/Server/issues/87
- ai api
> feat: ai api

- src/main/java/com/example/springserver/SpringServerApplication.java
- src/main/java/com/example/springserver/application/admin/AdminController.java
- src/main/java/com/example/springserver/application/ai/AiController.java
- src/main/java/com/example/springserver/domain/admin/service/AdminService.java
- src/main/java/com/example/springserver/domain/ai/converter/AiConverter.java
- src/main/java/com/example/springserver/domain/ai/dto/AiResponseDTO.java
- src/main/java/com/example/springserver/domain/ai/service/AiService.java
- src/main/java/com/example/springserver/domain/cafe/repository/CafeRepository.java
- src/main/java/com/example/springserver/domain/cafe/service/CafeService.java
- src/main/java/com/example/springserver/global/scheduling/KeywordScheduler.java
- https://github.com/CookieMoa/Server/issues/89
- 관리자 ai 정보 조회
> feat: 관리자 ai 정보 조회

- build.gradle
- src/main/java/com/example/springserver/application/admin/AdminController.java
- src/main/java/com/example/springserver/domain/admin/dto/AdminResponseDTO.java
- src/main/java/com/example/springserver/domain/admin/service/AdminService.java
- src/main/java/com/example/springserver/domain/cafe/repository/ReviewRepository.java
- src/main/java/com/example/springserver/domain/cafe/service/ReviewService.java
- https://github.com/CookieMoa/Server/issues/91
- 키워드 업데이트api
> feat: 키워드 업데이트api

- review_keywords_2025-05-15.csv
- src/main/java/com/example/springserver/application/admin/AdminController.java
- src/main/java/com/example/springserver/application/ai/AiController.java
- src/main/java/com/example/springserver/domain/admin/service/AdminService.java
- src/main/java/com/example/springserver/domain/ai/service/AiService.java
- https://github.com/CookieMoa/Server/issues/93
- 모델 학습
> feat: 모델 학습

- src/main/java/com/example/springserver/application/admin/AdminController.java
- src/main/java/com/example/springserver/domain/admin/converter/AdminConverter.java
- src/main/java/com/example/springserver/domain/admin/dto/AdminResponseDTO.java
- src/main/java/com/example/springserver/domain/admin/service/AdminService.java
- src/main/java/com/example/springserver/domain/cafe/converter/CafeConverter.java
- src/main/java/com/example/springserver/domain/cafe/dto/CafeResponseDTO.java
- src/main/java/com/example/springserver/domain/cafe/repository/CafeRepository.java
- src/main/java/com/example/springserver/domain/cafe/repository/ReviewRepository.java
- src/main/java/com/example/springserver/domain/cafe/service/ReviewService.java
- src/main/java/com/example/springserver/domain/customer/converter/CustomerConverter.java
- src/main/java/com/example/springserver/domain/customer/dto/CustomerResponseDTO.java
- src/main/java/com/example/springserver/domain/customer/service/CustomerService.java
- src/main/java/com/example/springserver/entity/Review.java
- https://github.com/CookieMoa/Server/issues/97
- 관리자 api 추가 및 수정
> feat: 관리자 api 추가 및 수정

- src/main/java/com/example/springserver/domain/ai/service/AiService.java
- src/main/java/com/example/springserver/domain/cafe/service/CafeService.java
- https://github.com/CookieMoa/Server/issues/101
- 욕설 탐지 수정
> fix: 욕설 탐지

- src/main/java/com/example/springserver/application/admin/AdminController.java
- src/main/java/com/example/springserver/domain/admin/service/AdminService.java
- src/main/java/com/example/springserver/domain/customer/converter/CustomerConverter.java
- src/main/java/com/example/springserver/domain/customer/dto/CustomerResponseDTO.java
- https://github.com/CookieMoa/Server/issues/103
- 유저 랭크 api
> feat: 유저 랭크 api

- src/main/java/com/example/springserver/domain/admin/service/AdminService.java
- src/main/java/com/example/springserver/domain/keyword/repository/KeywordMappingRepository.java
- src/main/java/com/example/springserver/domain/keyword/service/KeywordService.java
- https://github.com/CookieMoa/Server/issues/108
- 카페 키워드 중복 문제 해결
> fix: 카페 키워드 중복
